apiVersion: v1
kind: Service
metadata:
  labels:
    app: nginx
  name: nginx
spec:
  ports:
  - name: nginx
    port: 80
    targetPort: 80
  selector:
    app: nginx
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: nginx
  labels:
    app: nginx
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        securityContext:
          privileged: false
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: praqma-multitool
  labels:
    app: praqma-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: praqma-multitool
  template:
    metadata:
      labels:
        app: praqma-multitool
    spec:
      containers:
      - name: praqma-multitool
        image: praqma/network-multitool
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        securityContext:
          privileged: false