kind: Deployment
apiVersion: apps/v1
metadata:
  name: praqma-multitool
  labels:
    app: praqma-multitool
spec:
  replicas: 1
  selector:
    matchLabels:
      app: praqma-multitool
  template:
    metadata:
      labels:
        app: praqma-multitool
    spec:
      containers:
      - name: praqma-multitool
        image: praqma/network-multitool
        imagePullPolicy: IfNotPresent
        resources:
          requests:
            cpu: 250m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 1Gi
        securityContext:
          privileged: false